services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

volumes:
  mysql-data:

networks:
  backend-network:
    driver: bridge
